"""Added column 'disabled' in User table

Revision ID: 095be3b6719f
Revises: 3e35fd114f55
Create Date: 2021-09-19 21:55:47.612565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095be3b6719f'
down_revision = '3e35fd114f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
