"""change column user_id in table UserDetail

Revision ID: 3e35fd114f55
Revises: c842b06f9520
Create Date: 2021-09-19 13:32:33.742658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e35fd114f55'
down_revision = 'c842b06f9520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_detail', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_detail', type_='unique')
    # ### end Alembic commands ###
